---
"on":
  push:
    paths-ignore:
      - "**.md"
      - docs/*
  pull_request:
    paths-ignore:
      - "**.md"
      - docs/*
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v8.3.2
      - name: Install dependencies
        run: |
          uv sync --extra=dev
      - name: Test
        run: |
          source .venv/bin/activate
          pytest --cov
      - uses: codecov/codecov-action@v4

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v8.3.2
      - name: Build
        run: |
          uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: startsWith(github.ref, 'refs/tags/')
      - uses: actions/upload-artifact@v4
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          path: |
            dist/*
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*

  deploy-aur:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: Freed-Wu/update-aur-package@v1.0.11
        if: startsWith(github.ref, 'refs/tags/')
        with:
          package_name: termux-language-server
          ssh_private_key: ${{secrets.AUR_SSH_PRIVATE_KEY}}

  deploy-nur:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Trigger Workflow
        run: >
          curl -X POST -d '{"ref":"main"}'
          -H "Accept: application/vnd.github.v3+json"
          -H "Authorization: Bearer ${{secrets.GH_TOKEN}}"
          https://api.github.com/repos/Freed-Wu/nur-packages/actions/workflows/version.yml/dispatches
